name: Kommando
main: CommandTracker\CommandTracker
version: "1.3"
api: [1.10.0]
load: STARTUP
author: ScottHandley Edit by QueenMC
description: Logs commands issued by players and console operators. Censors commands for inappropriate language.
commands:
    track:
        description: "Administer command auditing and censorship"
        usage: "/track ?|subcmd [options]"
        permissions: commandtracker.commands.track
permissions:
    commandtracker.commands.track:
        default: false
        description: "Grants administrators to manage command tracking behavior"