name: Friends
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1]
version: 1.0
main: Bluplayz\Friends
author: Bluplayz
website: http://youtube.com/Bluplayz
commands:
    friend:
        description: FreundesSystem
        aliases: [f, freunde, friends]
