name: HerzenTag
version: 1.2
api: 1.3.1
author: QueenMc
description: Shows Player's Health beside NameTag
main: HealthTag\HealthTag

commands:
 ht:
  default: op
  description: "Enable or disable healthtag"
  usage: "/ht"
