name: EmptyWorld
main: aliuly\emptyworld\Main
version: 1.1.1
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1]
description: An empty world generator
author: aliuly
load: STARTUP
website: https://github.com/Muirfield/EmptyWorld
