name: FactionsPro
author: Tethered_
description: A Plugin For Easily Managing Factions
version: 1.6.3
main: FactionsPro\FactionMain
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
