name: BuyCraft
main: buycraft\BuyCraft
version: 1.2.2
author: Falkirks
api: [1.0.0]
load: POSTWORLD
permissions:
 buycraft:
  default: op
  description: Top level BuyCraft permission
  children:
   buycraft.admin:
    default: op
   buycraft.buy:
    default: true
