main: aliuly\grabbag\Main
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1]
load: POSTWORLD

name: GrabBag
description: Collection of miscellaneous commands and listener modules
version: 2.3.0
author: aliuly
website: https://github.com/Muirfield/GrabBag
softdepend: FastTransfer
