name: DreambuildChat
main: ChatToolsPro\Main
version: 1.3
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1]
load: POSTWORLD
author: paetti
description: Chat Tools by paetti.
commands:
 dreamchat:
  description: §aChatToolsPro Help
  usage: "/ctp <1/2/3/4/5>."
  aliases: [ctp]
  permission: chattoolspro.ctp
 checkop:
  description: §aCheck if a Player is OP or not.
  usage: "/checkop <Player>."
  permission: chattoolspro.checkop
 hilfe:
  description: §aAdds [NeedsHelp] Tag to a Name
  usage: "/helpme."
  permission: chattoolspro.helpme
 support:
  description: §aBroadcasts a Message as [Support]
  usage: "/support <Message>."
  aliases: [supportsay, saysupport]
  permission: chattoolspro.supportsay
 warning:
  description: §aBroadcasts a Message as [Warning]
  usage: "/warning <Message>."
  aliases: [warnsay]
  permission: chattoolspro.warning
 durchsage:
  description: §aBroadcasts a Message as [Announcement]
  usage: "/announcement."
  aliases: [sayannounce]
  permission: chattoolspro.announcement
 alarm:
  description: §aBroadcasts a Message as [ALERT]
  usage: "/alert <Message>."
  aliases: [alertsay]
  permission: chattoolspro.alert
 information:
  description: §aBroadcasts a Message as [Info]
  usage: "/info <Message>."
  aliases: [infosay]
  permission: chattoolspro.info
 erledigt:
  description: §aRemoves [NeedsHelp] Tag from a Name
  aliases: [donehelp]
  usage: "/helpdone."
  permission: chattoolspro.done
 serversay:
  description: §aBroadcasts a Message as [Server]
  usage: "/serversay."
  aliases: [sayserver]
  permission: chattoolspro.serversay
 staffsay:
  description: §aBroadcasts a Message as [Staff]
  usage: "/staffsay."
  aliases: [saystaff]
  permission: chattoolspro.staffsay
 warnung:
  description: §cWarns a Player
  usage: "/warn <Player> <Reason>."
  permission: chattoolspro.warn
 vmsg:
  description: §aSends an anonymous Message to a Player without the Sender Name
  usage: "/vmsg <Player> <Message>."
  permission: chattoolspro.vmsg
 chatsay:
  description: §aBroadcast a Message without any Tag
  usage: "/chatsay <Message>."
  permission: chattoolspro.chatsay
 tipgive:
  description: §a Give an Player a Tip
  usage: "/tipgive <Player> <Tip>."
  permission: chattoolspro.tipgive
 setzenick:
  description: §aSets an Nick
  usage: "/setnick <Nick>."
  permission: chattoolspro.setnick
 delnick:
  description: §aDelete Nick of yourself or another Player
  usage: "/delnick [Player]."
  permission: chattoolspro.del
 spam:
  description: §aSpam
  usage: "/spam."
  permission: chattoolspro.spam
 sayas:
  description: §aSend a Message as another Player
  usage: "/sayas <Player> <Message>."
  permission: chattoolspro.sayas
 spammsg:
  description: §aSend a Message to another Player more times at once
  usage: "/spammsg <Player> <Message>."
  permission: chattoolspro.spammsg
 spamsay:
  description: §aSpams a Message into the chat
  usage: "/spamsay <Message>."
  permission: chattoolspro.spamsay
 leeren:
  description: §aClears the Chat.
  usage: "/clearchat."
  permission: chattoolspro.clearchat
 hug:
  description: §aHug a Player.
  usage: "/hug <Player>."
  permission: chattoolspro.hug
 fakeop:
  description: §aFake op a Player.
  usage: "/opfake <Player>."
  permission: chattoolspro.opfake
 deopfake:
  description: §aFake Deop a Player.
  usage: "/deopfake <Player>."
  permission: chattoolspro.deopfake
 melden:
  description: §aReport a Player
  usage: "/report <Player> <Reason>."
  permission: chattoolspro.report
 ops:
  description: §aSee online OP's by a List
  usage: "/ops"
  permission: chattoolspro.ops
 lockchat:
  description: §aSee online OP's
  usage: "/lockchat <lock/unlock>"
  permission: chattoolspro.lockchat
 senden:
  description: §aSend Message to Player without Prefix
  usage: "/send <Player> <Message>."
  permission: chattoolspro.send
permissions:
 chattoolspro.ctp:
  default: true
 chattoolspro.helpme:
  default: true
 chattoolspro.done:
  default: true
 chattoolspro.announcement:
  default: op
 chattoolspro.serversay:
  default: op
 chattoolspro.staffsay:
  default: op
 chattoolspro.support:
  default: op
 chattoolspro.warning:
  default: op
 chattoolspro.warn:
  default: op
 chattoolspro.vmsg:
  default: op
 chattoolspro.chatsay:
  default: op
 chattoolspro.alert:
  default: op
 chattoolspro.info:
  default: op
 chattoolspro.tipgive:
  default: true
 chattoolspro.setnick:
  default: op
 chattoolspro.delnick:
  default: op
 chattoolspro.sayas:
  default: op
 chattoolspro.report:
  default: true
 chattoolspro.ops:
  default: true
 chattoolspro.spam:
  default: op
 chattoolspro.clearchat:
  default: op
 chattoolspro.hug:
  default: true
 chattoolspro.spammsg:
  default: op
 chattoolspro.spamsay:
  default: op
 chattoolspro.opfake:
  default: op
 chattoolspro.deopfake:
  default: op
 chattoolspro.checkop:
  default: op
 chattoolspro.lockchat:
  default: op
 chattoolspro.send:
  default: op
