name: VoteReward
main: LDX\VoteReward\Main
version: 3.0.2
api: [1.12.0, 2.0.0]
author: LDX
website: "http://votereward.mcpe.me"
load: POSTWORLD
commands:
  vote:
    usage: "/vote"
    description: "Checks to see if you've voted yet."
    permission: votereward.command.vote
permissions:
  votereward:
    default: false
    description: "Allows access to all VoteReward features."
    children:
      votereward.command:
        default: false
        description: "Allows access to all VoteReward commands."
        children:
          votereward.command.vote:
            default: true
            description: "Allows access to using the vote command."
          votereward.command.reload:
            default: op
            description: "Allows access to the vote reload subcommand."