name: CommandRepeater
main: CommandRepeater\Main
version: 1.0.1
api: 1.8.0
author: iksaku

permissions:
    commandrepeater:
        default: true
        description: "Allow you to access the command repeater"