name: CommandRepeater
main: CommandRepeater\Main
version: 1.0.1
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1]
author: iksaku

permissions:
    commandrepeater:
        default: true
        description: "Allow you to access the command repeater"
