name: BlockSniffer
author: DRedDog
description: Trace block interaction!
version: 1.0.0
main: BlockSniffer\Main
api: [1.12.0]
commands:
  bs:
    description: Use /bs here
    permission: blocksniffer
permissions:
  blocksniffer:
    default: true
    description: "Allows the use of /bs here"