main: aliuly\worldprotect\Main
api: [1.10.0,1.12.0]
load: STARTUP

name: WorldProtect
description: protect worlds from griefers, pvp, limits and borders
version: 2.2.0
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/WorldProtect

commands:
  worldprotect:
    description: Manage worlds
    usage: "/wp <help|sub-cmd> [options]"
    permission: wp.cmd.all
    aliases: [wp]

permissions:
  wp.motd:
    default: true
    description: "Display MOTD"
  wp.cmd.all:
    default: op
    description: "Allow access to protect command"
  wp.cmd.protect:
    default: op
    description: "Change protect mode"
  wp.cmd.protect.auth:
    default: op
    description: "Permit place/destroy in protected worlds"
  wp.cmd.border:
    default: op
    description: "Allow contfol of border functionality"
  wp.cmd.pvp:
    default: op
    description: "Allow PvP controls"
  wp.cmd.noexplode:
    default: op
    description: "Allow NoExplode controls"
  wp.cmd.limit:
    default: op
    description: "Allow control to limit functionality"
  wp.cmd.wpmotd:
    default: op
    description: "Allow editing the motd"
  wp.cmd.addrm:
    default: op
    description: "Allow modifying the auth list"
  wp.cmd.unbreakable:
    default: op
    description: "Modify unbreakable block list"
  wp.cmd.bancmd:
    default: op
    description: "Ban/unban commands"
  wp.cmd.banitem:
    default: op
    description: "Ban/unban items"
  wp.cmd.info:
    default: true
    description: "Show WP config info"
  wp.cmd.gm:
    default: op
    description: "Allow setting a per-world gamemode"
  wp.cmd.gm.exempt:
    default: false
    description: "Users with this permissions will ignore per world gm"
